
CREATE TABLE STUDENT_INFO
(
    RNO INT PRIMARY KEY,
    NAME VARCHAR(50),
    BRANCH VARCHAR(10)
);



CREATE TABLE RESULT
(
    RNO INT,
    SPI DECIMAL(3,2),
    FOREIGN KEY (RNO) REFERENCES STUDENT_INFO(RNO)
);



INSERT INTO STUDENT_INFO VALUES
(101,'Aarav','CE'),
(102,'Priya','IT'),
(103,'Rahul','ME'),
(104,'Sneha','CE'),
(105,'Karan','EC'),
(106,'Riya','ME'),
(107,'Vivek','CE'),
(108,'Neha','IT'),
(109,'Yash','EC'),
(110,'Anjali','CE');


INSERT INTO RESULT VALUES
(101,8.50),
(102,7.20),
(103,6.80),
(104,9.10),
(105,7.90),
(106,8.20),
(107,9.50),
(108,6.90),
(109,8.70),
(110,7.80);



-- 1. Cross Join (Cartesian Product)

SELECT *
FROM STUDENT_INFO
CROSS JOIN RESULT;


-- 2. Inner Join

SELECT *
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO=R.RNO;


-- 3. Left Outer Join

SELECT *
FROM STUDENT_INFO S
LEFT JOIN RESULT R
ON S.RNO=R.RNO;


-- 4. Right Outer Join

SELECT *
FROM STUDENT_INFO S
RIGHT JOIN RESULT R
ON S.RNO=R.RNO;


-- 5. Full Outer Join (MySQL)

SELECT *
FROM STUDENT_INFO S
LEFT JOIN RESULT R
ON S.RNO=R.RNO

UNION

SELECT *
FROM STUDENT_INFO S
RIGHT JOIN RESULT R
ON S.RNO=R.RNO;


-- 6. Display Rno, Name, Branch and SPI

SELECT S.RNO,S.NAME,S.BRANCH,R.SPI
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO=R.RNO;


-- 7. CE Branch Students

SELECT S.RNO,S.NAME,S.BRANCH,R.SPI
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO=R.RNO
WHERE BRANCH='CE';


-- 8. Students Other Than EC Branch

SELECT S.RNO,S.NAME,S.BRANCH,R.SPI
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO=R.RNO
WHERE BRANCH<>'EC';


-- 9. SPI Greater Than 8

SELECT S.RNO,S.NAME,R.SPI
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO=R.RNO
WHERE SPI>8;


-- 10. SPI Less Than 8

SELECT S.RNO,S.NAME,S.BRANCH
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO=R.RNO
WHERE SPI<8;


-- 11. Average Result of Each Branch

SELECT BRANCH,AVG(SPI) AS AVERAGE_SPI
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO=R.RNO
GROUP BY BRANCH;


-- 12. Average Result of CE and ME Branch

SELECT BRANCH,AVG(SPI) AS AVERAGE_SPI
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO=R.RNO
WHERE BRANCH IN ('CE','ME')
GROUP BY BRANCH;


-- 13. Maximum and Minimum SPI of Each Branch

SELECT BRANCH,
MAX(SPI) AS MAX_SPI,
MIN(SPI) AS MIN_SPI
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO=R.RNO
GROUP BY BRANCH;


--14. Branch-wise Student Count Descending

SELECT BRANCH,
COUNT(*) AS TOTAL_STUDENTS
FROM STUDENT_INFO
GROUP BY BRANCH
ORDER BY TOTAL_STUDENTS DESC;


--15. Branch-wise Total SPI

SELECT BRANCH,
SUM(SPI) AS TOTAL_SPI
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO=R.RNO
GROUP BY BRANCH;



--16. Branch-wise Students Having SPI Greater Than 8

SELECT BRANCH,
COUNT(*) AS STUDENT_COUNT
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO=R.RNO
WHERE SPI>8
GROUP BY BRANCH;


--17. Branch-wise Students Having SPI Less Than 8

SELECT BRANCH,
COUNT(*) AS STUDENT_COUNT
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO=R.RNO
WHERE SPI<8
GROUP BY BRANCH;


--18. Branch-wise Average SPI Greater Than 7

SELECT BRANCH,
AVG(SPI) AS AVERAGE_SPI
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO=R.RNO
GROUP BY BRANCH
HAVING AVG(SPI)>7;


--19. Branches Having More Than One Student

SELECT BRANCH,
COUNT(*) AS TOTAL_STUDENTS
FROM STUDENT_INFO
GROUP BY BRANCH
HAVING COUNT(*)>1;


--20. Branches Where Maximum SPI Greater Than 9

SELECT BRANCH,
MAX(SPI) AS MAX_SPI
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO=R.RNO
GROUP BY BRANCH
HAVING MAX(SPI)>9;

--21. Average Result of Each Branch (Ascending)

SELECT BRANCH,
AVG(SPI) AS AVERAGE_SPI
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO=R.RNO
GROUP BY BRANCH
ORDER BY AVERAGE_SPI ASC;


--22. Highest SPI from Each Branch (Descending)

SELECT BRANCH,
MAX(SPI) AS HIGHEST_SPI
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO=R.RNO
GROUP BY BRANCH
ORDER BY HIGHEST_SPI DESC;


--23. Average Result of Each Branch (Ascending)

SELECT BRANCH,
AVG(SPI) AS AVERAGE_SPI
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO=R.RNO
GROUP BY BRANCH
ORDER BY AVERAGE_SPI ASC;


--24. Highest SPI from Each Branch (Descending)

SELECT BRANCH,
MAX(SPI) AS HIGHEST_SPI
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO=R.RNO
GROUP BY BRANCH
ORDER BY HIGHEST_SPI DESC;


--25. Difference Between Maximum and Minimum SPI Greater Than 1

SELECT BRANCH,
MAX(SPI) AS MAX_SPI,
MIN(SPI) AS MIN_SPI,
(MAX(SPI)-MIN(SPI)) AS DIFFERENCE
FROM STUDENT_INFO S
INNER JOIN RESULT R
ON S.RNO=R.RNO
GROUP BY BRANCH
HAVING (MAX(SPI)-MIN(SPI))>1;
