--1. Combine information from Person and Department table using cross join or Cartesian product.

SELECT * FROM PERSON,DEPARTMENT

--2. Find all persons with their department name

SELECT DEPARTMENTNAME ,PERSONNAME FROM PERSON JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID

--3. Find all persons with their department name & code.

SELECT PERSONNAME,DEPARTMENTNAME,DEPARTMENT.DEPARTMENTID FROM PERSON LEFT JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID

--4. Find all persons with their department code and location.

SELECT PERSONNAME,DEPARTMENT.DEPARTMENTCODE,DEPARTMENT.LOCATION FROM PERSON LEFT JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID

--5. Find the detail of the person who belongs to Mechanical department.

SELECT * FROM PERSON FULL JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
WHERE DEPARTMENTCODE = 'ME'

--6. Final person’s name, department code and salary who lives in Ahmedabad city.

SELECT PERSONNAME,DEPARTMENTCODE , SALARY FROM PERSON FULL JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
WHERE CITY = 'AHMEDABAD'

--7. Find the person's name whose department is in C-Block.

SELECT PERSONNAME FROM PERSON JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
WHERE DEPARTMENT.LOCATION = 'C-BLOCK'

--8. Retrieve person name, salary & department name who belongs to Jamnagar city.

SELECT PERSONNAME,SALARY,DEPARTMENTNAME FROM PERSON JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
WHERE CITY = 'JAMNAGAR'

--9. Retrieve person’s detail who joined the Civil department after 1-Aug-2001.

SELECT * FROM PERSON FULL JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
WHERE JOININGDATE > '01-08-2001' AND DEPARTMENTNAME = 'CIVIL'

--10. Display all the person's name with the department whose joining date difference with the current date is more than 25 years.

SELECT PERSONNAME , DEPARTMENTNAME FROM PERSON LEFT JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
WHERE DATEDIFF(YEAR,JOININGDATE,GETDATE()) > 25

--11. Find department wise person counts.

SELECT DEPARTMENTNAME,COUNT(PERSONID) FROM PERSON JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
GROUP BY DEPARTMENTNAME

--12. Give department wise maximum & minimum salary with department name.

SELECT DEPARTMENTNAME,MAX(SALARY) ,MIN(SALARY )FROM PERSON JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
GROUP BY DEPARTMENTNAME

--13. Find city wise total, average, maximum and minimum salary.

SELECT CITY,MAX(SALARY) ,MIN(SALARY ),AVG(SALARY) ,SUM(SALARY) FROM PERSON JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
GROUP BY CITY

--14. Find the average salary of a person who belongs to Ahmedabad city.

SELECT CITY,AVG(SALARY) FROM PERSON
WHERE CITY = 'AHMEDABAD'
GROUP BY CITY

--15. Produce Output Like: <PersonName> lives in <City> and works in <DepartmentName> Department. (In single column)

SELECT FORMAT(PERSONNAME , CITY , DEPARTMENTNAME) FROM PERSON JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID

--16. Produce Output Like: <PersonName> earns <Salary> from <DepartmentName> department monthly. (In single column)

SELECT FORMAT(PERSONNAME , CITY , DEPARTMENTNAME) FROM PERSON JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID

--17. Find city & department wise total, average & maximum salaries.

SELECT CITY,DEPARTMENTNAME,SUM(SALARY),AVG(SALARY),MAX(SALARY) FROM PERSON JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
GROUP BY CITY,DEPARTMENTNAME

--18. Find all persons who do not belong to any department.

SELECT PERSONNAME FROM PERSON  LEFT JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
WHERE PERSON.DEPARTMENTID IS NULL 

--19. Find all departments whose total salary is exceeding 100000.

SELECT DEPARTMENTNAME,SUM(SALARY) FROM PERSON LEFT JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
GROUP BY DEPARTMENTNAME

--20. List all departments who have no person.

SELECT DEPARTMENTNAME ,COUNT(PERSONID) FROM PERSON  LEFT JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
GROUP BY DEPARTMENTNAME
HAVING COUNT(PERSONID) = 0

--21. List out department names in which more than two persons are working.

SELECT department
FROM EMPLOYEE
GROUP BY department
HAVING COUNT(*) > 2;
--22. Give a 10% increment in the computer department employee’s salary. (Use Update)

UPDATE EMPLOYEE
SET salary = salary * 1.10
WHERE department = 'Computer';