CREATE TABLE STUDENT(
STDID INT,
SNAME VARCHAR(50), 
CITY VARCHAR(50), 
SPI DECIMAL(4,2), 
BRANCH VARCHAR(50));

INSERT INTO STUDENT

VALUES(101, 'HETVI', 'RAJKOT', 7.40, 'COMPUTER'),
(102, 'RAJ', 'MORBI', 9.50, 'MECHANICAL'), 
(103, 'VISHAL', 'RAJKOT' ,9.00, 'CIVIL'), 
(104, 'DEEP', 'SURAT', 8.80, 'COMPUTER'),
(105, 'DHARMIK', 'BARODA', 8.80, 'CHEMICAL'), 
(106, 'KRUNAL', 'VAPI', 9.00, 'CIVIL'), 
(107, 'RIYA', 'NAVSARI', 5.50, 'COMPUTER'), 
(108, 'VRUNDA', 'KUTCH', 7.60, 'ELECTRICAL'), 
(109, 'SMAIR', 'JAMNAGAR', 6.80, 'EC'),
(110, 'PARAG', 'SURAT', 7.00, 'CHEMICAL'), 
(111, 'HARSH', 'RAJKOT', 4.00, 'NULL');


-- From the table STUDENT perform the following queries:

-- Part – A:

-- 1. Display rank of students based on SPI.
SELECT STDID, SNAME, SPI,
RANK() OVER (ORDER BY SPI DESC) AS RANK_NO
FROM STUDENT

-- 2. Display dense rank of students based on SPI.
SELECT STDID, SNAME, SPI,
DENSE_RANK() OVER (ORDER BY SPI DESC) AS DENSE_RANK_NO
FROM STUDENT

-- 3. Display sequential number for each student record.
SELECT STDID, SNAME, SPI,
ROW_NUMBER() OVER (ORDER BY STDID) AS SEQ_NO
FROM STUDENT

-- 4. Display branch-wise rank of students.
SELECT STDID, SNAME, BRANCH, SPI,
RANK() OVER (PARTITION BY BRANCH ORDER BY SPI DESC) AS BRANCH_RANK
FROM STUDENT

-- 5. Display branch-wise dense ranking of students.
SELECT STDID, SNAME, BRANCH, SPI,
DENSE_RANK() OVER
(PARTITION BY BRANCH ORDER BY SPI DESC) AS BRANCH_DENSE_RANK
FROM STUDENT

-- 6. Display branch-wise sequential numbering of students.
SELECT STDID, SNAME, BRANCH, SPI,
ROW_NUMBER() OVER
(PARTITION BY BRANCH ORDER BY SPI DESC) AS BRANCH_SEQ_NO
FROM STUDENT

-- 7. Display SNAME, Current SPI, Previous SPI and SPI Difference with previous student in ascending order of
-- SPI.
SELECT SNAME,
SPI AS CURRENT_SPI,
LAG(SPI) OVER (ORDER BY SPI ASC) AS PREVIOUS_SPI,
SPI - LAG(SPI) OVER (ORDER BY SPI ASC) AS SPI_DIFFERENCE
FROM STUDENT
ORDER BY SPI ASC

-- 8. Display SNAME, Current SPI, Next SPI and SPI Difference with next student in descending order of SPI.
SELECT SNAME,
SPI AS CURRENT_SPI,
LEAD(SPI) OVER (ORDER BY SPI DESC) AS NEXT_SPI,
SPI - LEAD(SPI) OVER (ORDER BY SPI DESC) AS SPI_DIFFERENCE
FROM STUDENT
ORDER BY SPI DESC

-- 9. Display top 3 students based on SPI.
SELECT *
FROM (
SELECT STDID, SNAME, CITY, SPI, BRANCH,
RANK() OVER (ORDER BY SPI DESC) AS RANK_NO
FROM STUDENT
) AS T
WHERE RANK_NO <= 3

-- 10. Display top 2 students from each branch.
SELECT *
FROM (
SELECT STDID, SNAME, CITY, SPI, BRANCH,
RANK() OVER
(PARTITION BY BRANCH ORDER BY SPI DESC) AS BRANCH_RANK
FROM STUDENT
) AS T
WHERE BRANCH_RANK <= 2


-- Part – B:
-- 11. Display 5th highest SPI.

SELECT TOP 5 SPI
FROM (
    SELECT DISTINCT TOP 5 SPI
    FROM STUDENT
    ORDER BY SPI DESC
) AS T
ORDER BY SPI ASC

-- 12. Display 6th highest SPI.
SELECT TOP 6 SPI
FROM (
    SELECT DISTINCT TOP 6 SPI
    FROM STUDENT
    ORDER BY SPI DESC
) AS T
ORDER BY SPI ASC

-- 13. Display students having same ranking.
SELECT *
FROM (
SELECT STDID, SNAME, SPI, BRANCH,
RANK() OVER (ORDER BY SPI DESC) AS RANK_NO
FROM STUDENT
) AS T
WHERE SPI IN (
SELECT SPI
FROM STUDENT
GROUP BY SPI
HAVING COUNT(*) > 1
)

-- 14. Display SNAME, Previous SPI, Current SPI and Next SPI based on ascending order of SPI.
SELECT SNAME,
LAG(SPI) OVER (ORDER BY SPI ASC) AS PREVIOUS_SPI,
SPI AS CURRENT_SPI,
LEAD(SPI) OVER (ORDER BY SPI ASC) AS NEXT_SPI
FROM STUDENT
ORDER BY SPI ASC

-- 15. Display topper of each branch.
SELECT STDID, SNAME, BRANCH, SPI
FROM (
SELECT STDID, SNAME, BRANCH, SPI,
RANK() OVER
(PARTITION BY BRANCH ORDER BY SPI DESC) AS BRANCH_RANK
FROM STUDENT
) AS T
WHERE BRANCH_RANK = 1

-- Part – C:
-- 16. Display students whose SPI is greater than the previous student and less than the next student.
SELECT *
FROM (
SELECT STDID,
SNAME,
SPI,
LAG(SPI) OVER (ORDER BY SPI ASC) AS PREVIOUS_SPI,
LEAD(SPI) OVER (ORDER BY SPI ASC) AS NEXT_SPI
FROM STUDENT
) AS T
WHERE SPI > PREVIOUS_SPI
AND SPI < NEXT_SPI

-- 17. Display branch-wise second topper students.
SELECT STDID, SNAME, BRANCH, SPI
FROM (
SELECT STDID, SNAME, BRANCH, SPI,
DENSE_RANK() OVER
(PARTITION BY BRANCH ORDER BY SPI DESC) AS BRANCH_RANK
FROM STUDENT
) AS T
WHERE BRANCH_RANK = 2

-- 18. Display students whose rank and dense rank are different.
SELECT *
FROM (
SELECT STDID,
SNAME,
SPI,
RANK() OVER (ORDER BY SPI DESC) AS RANK_NO,
DENSE_RANK() OVER (ORDER BY SPI DESC) AS DENSE_RANK_NO
FROM STUDENT
) AS T
WHERE RANK_NO <> DENSE_RANK_NO


-- 19. Display consecutive students having same branch ordered by SPI.
SELECT STDID, SNAME, BRANCH, SPI
FROM (
SELECT STDID,
SNAME,
BRANCH,
SPI,
LAG(BRANCH) OVER (ORDER BY SPI ASC) AS PREVIOUS_BRANCH,
LEAD(BRANCH) OVER (ORDER BY SPI ASC) AS NEXT_BRANCH
FROM STUDENT
) AS T
WHERE BRANCH = PREVIOUS_BRANCH
OR BRANCH = NEXT_BRANCH
ORDER BY SPI ASC


-- 20. Display students whose SPI difference with previous student is maximum.
SELECT *
FROM (
SELECT STDID,
SNAME,
SPI,
SPI - LAG(SPI) OVER (ORDER BY SPI ASC) AS SPI_DIFFERENCE
FROM STUDENT
) AS T
WHERE SPI_DIFFERENCE = (
SELECT MAX(SPI_DIFFERENCE)
FROM (
SELECT SPI - LAG(SPI) OVER (ORDER BY SPI ASC) AS SPI_DIFFERENCE
FROM STUDENT
) AS X
)