CREATE TABLE STUDENT 
(
    STDID INT,
    SNAME VARCHAR(50),
    CITY VARCHAR(50),
    SPI DECIMAL(4,2),
    BRANCH VARCHAR(50)
)

INSERT INTO STUDENT
VALUES 
(101,'HETVI','RAJKOT',7.40,'COMPUTER'),
(102,'RAJ','MORBI',9.50,'MECHANICAL'),
(103,'VISHAL','RAJKOT',9.00,'CIVIL'),
(104,'DEEP','SURAT',8.80,'COMPUTER'),
(105,'DHARMIK','BARODA',8.80,'CHEMICAL'),
(106,'KRUNAL','VAPI',9.00,'CIVIL'),
(107,'RIYA','NAVSARI',5.50,'COMPUTER'),
(108,'VRUNDA','KUTCH',7.60,'ELECTRICAL'),
(109,'SMAIR','JAMNAGAR',6.80,'EC'),
(110,'PARAG','SURAT',7.00,'CHEMICAL')

INSERT INTO STUDENT(STDID,SNAME,CITY,SPI)
VALUES
(111,'HARSH','RAJKOT',4.00)

SELECT * FROM STUDENT


--   PART - A


-- 1. Display all student records 

CREATE FUNCTION FN_ALL_STUDENTS()
RETURNS TABLE
AS
RETURN
(
    SELECT *
    FROM STUDENT
)

SELECT * FROM FN_ALL_STUDENTS()


-- 2. Accept CITY and return all students from that city 

CREATE FUNCTION FN_STUDENT_BY_CITY
(
    @CITY VARCHAR(50)
)
RETURNS TABLE
AS
RETURN
(
    SELECT *
    FROM STUDENT
    WHERE CITY = @CITY
)

SELECT * FROM FN_STUDENT_BY_CITY('RAJKOT')


-- 3. Accept BRANCH and return all students from that branch 

CREATE FUNCTION FN_STUDENT_BY_BRANCH
(
    @BRANCH VARCHAR(50)
)
RETURNS TABLE
AS
RETURN
(
    SELECT *
    FROM STUDENT
    WHERE BRANCH = @BRANCH
)

SELECT * FROM FN_STUDENT_BY_BRANCH('COMPUTER')


-- 4. Accept SPI and return students whose SPI is greater 

CREATE FUNCTION FN_SPI_GREATER
(
    @SPI DECIMAL(4,2)
)
RETURNS TABLE
AS
RETURN
(
    SELECT *
    FROM STUDENT
    WHERE SPI > @SPI
)

SELECT * FROM FN_SPI_GREATER(8.00)


-- 5. Accept MIN_SPI and MAX_SPI and return students whose SPI lies between the given range */

CREATE FUNCTION FN_SPI_RANGE
(
    @MIN_SPI DECIMAL(4,2),
    @MAX_SPI DECIMAL(4,2)
)
RETURNS TABLE
AS
RETURN
(
    SELECT *
    FROM STUDENT
    WHERE SPI BETWEEN @MIN_SPI AND @MAX_SPI
)

SELECT * FROM FN_SPI_RANGE(7.00,9.00)


--   PART - B


-- 6. Accept STDID and return details of that student 

CREATE FUNCTION FN_STUDENT_BY_ID
(
    @STDID INT
)
RETURNS TABLE
AS
RETURN
(
    SELECT *
    FROM STUDENT
    WHERE STDID = @STDID
)

SELECT * FROM FN_STUDENT_BY_ID(101)


-- 7. Accept CITY and return students whose SPI is greater than 7 from that city 

CREATE FUNCTION FN_CITY_SPI_GREATER_7
(
    @CITY VARCHAR(50)
)
RETURNS TABLE
AS
RETURN
(
    SELECT *
    FROM STUDENT
    WHERE CITY = @CITY
    AND SPI > 7
)

SELECT * FROM FN_CITY_SPI_GREATER_7('RAJKOT')


-- 8. Accept BRANCH and return students whose SPI is less than 8 from that branch 

CREATE FUNCTION FN_BRANCH_SPI_LESS_8
(
    @BRANCH VARCHAR(50)
)
RETURNS TABLE
AS
RETURN
(
    SELECT *
    FROM STUDENT
    WHERE BRANCH = @BRANCH
    AND SPI < 8
)

SELECT * FROM FN_BRANCH_SPI_LESS_8('COMPUTER')


-- 9. Accept TOPN and return top N students based on SPI 

CREATE FUNCTION FN_TOP_STUDENTS
(
    @TOPN INT
)
RETURNS TABLE
AS
RETURN
(
    SELECT TOP (@TOPN) *
    FROM STUDENT
    ORDER BY SPI DESC
)

SELECT * FROM FN_TOP_STUDENTS(5)


-- 10. Accept BRANCH and return highest SPI student from that branch 

CREATE FUNCTION FN_HIGHEST_SPI_BRANCH
(
    @BRANCH VARCHAR(50)
)
RETURNS TABLE
AS
RETURN
(
    SELECT TOP 1 *
    FROM STUDENT
    WHERE BRANCH = @BRANCH
    ORDER BY SPI DESC
)

SELECT * FROM FN_HIGHEST_SPI_BRANCH('CIVIL')


--   PART - C


-- 11. Accept CITY and return total students from that city 

CREATE FUNCTION FN_TOTAL_STUDENTS_CITY
(
    @CITY VARCHAR(50)
)
RETURNS TABLE
AS
RETURN
(
    SELECT COUNT(*) AS TOTAL_STUDENTS
    FROM STUDENT
    WHERE CITY = @CITY
)

SELECT * FROM FN_TOTAL_STUDENTS_CITY('RAJKOT')


-- 12. Accept BRANCH and return students ordered by SPI in descending order 

CREATE FUNCTION FN_BRANCH_SPI_DESC
(
    @BRANCH VARCHAR(50)
)
RETURNS TABLE
AS
RETURN
(
    SELECT *
    FROM STUDENT
    WHERE BRANCH = @BRANCH
)

SELECT *
FROM FN_BRANCH_SPI_DESC('COMPUTER')
ORDER BY SPI DESC


-- 13. Accept CITY and return top 3 students from that city based on SPI 

CREATE FUNCTION FN_TOP_3_CITY
(
    @CITY VARCHAR(50)
)
RETURNS TABLE
AS
RETURN
(
    SELECT TOP 3 *
    FROM STUDENT
    WHERE CITY = @CITY
    ORDER BY SPI DESC
)

SELECT * FROM FN_TOP_3_CITY('RAJKOT')


-- 14. Accept STDID and return student rank based on SPI 

CREATE FUNCTION FN_STUDENT_RANK
(
    @STDID INT
)
RETURNS TABLE
AS
RETURN
(
    SELECT STDID, SNAME, CITY, SPI, BRANCH,
           RANK() OVER (ORDER BY SPI DESC) AS STUDENT_RANK
    FROM STUDENT
    WHERE STDID = @STDID
)

SELECT * FROM FN_STUDENT_RANK(103)


-- 15. Accept BRANCH and return students having second highest SPI from that branch 

CREATE FUNCTION FN_SECOND_HIGHEST_BRANCH
(
    @BRANCH VARCHAR(50)
)
RETURNS TABLE
AS
RETURN
(
    SELECT STDID, SNAME, CITY, SPI, BRANCH
    FROM
    (
        SELECT *,
               DENSE_RANK() OVER (ORDER BY SPI DESC) AS SPI_RANK
        FROM STUDENT
        WHERE BRANCH = @BRANCH
    ) AS T
    WHERE SPI_RANK = 2
)

SELECT * FROM FN_SECOND_HIGHEST_BRANCH('COMPUTER')