CREATE TABLE TORDER(
ORDERID INT,
CUSTOMERNAME VARCHAR(50),
CITY VARCHAR(30),
TPRODUCT VARCHAR(50),
CATEGORY VARCHAR(30),
QUANTITY INT,
UNITPRICE DECIMAL(10,2),
ORDERDATE DATE,
PAYMENTMODE VARCHAR(20)

)
INSERT INTO TORDER
VALUES
(101,'DRASHTI','RAJKOT','TV','ELEC.',5,40000,'2025-03-02','UPI'),
(102,'KRUPALI','SURAT','REFRIGERATOR','ELEC.',34,40000,'2025-03-02','UPI'),
(103,'JANVI','AHMEDABAD','WASHING-MACHINE','ELEC.',1,50000,'2025-03-02','UPI'),
(104,'GOMTI','JAMNAGAR','TV','ELEC.',22,50000,'2025-06-06','CASH'),
(105,'AYUSHI','RAJKOT','AC','ELEC.',58,90000,'2025-07-31','UPI'),
(106,'SHAKTI','SURAT','AC','ELEC.',22,40000,'2025-04-11','CASH'),
(107,'KAVY','AHMEDABAD','PHONE','ELEC.',77,30000,'2025-12-02','CASH'),
(108,'JAY','RAJKOT','TV','ELEC.',5,45000,'2025-11-05','CASH'),
(109,'AARAV','AHMEDABAD','TABLET','ELEC.',1,140000,'2025-03-30','UPI'),
(110,'PRIYANSHI','BARODA','TV','ELEC.',4,60000,'2025-05-27','UPI');

-- 1. Display the Top 5 customers who purchased the highest total quantity.

SELECT TOP 5 CUSTOMERNAME,
SUM(QUANTITY) AS TOTAL_QTY
FROM TORDER
GROUP BY CUSTOMERNAME
ORDER BY TOTAL_QTY DESC;


-- 2. Display the Top 3 cities having the maximum number of orders.

SELECT TOP 3 CITY,
COUNT(*) AS TOTAL_ORDERS
FROM TORDER
GROUP BY CITY
ORDER BY TOTAL_ORDERS DESC;


-- 3. Display the Top 10 products having the highest total revenue.

SELECT TOP 10 TPRODUCT,
SUM(QUANTITY * UNITPRICE) AS TOTAL_REVENUE
FROM TORDER
GROUP BY TPRODUCT
ORDER BY TOTAL_REVENUE DESC;


-- 4. Display the Top 5 categories having the highest average unit price.

SELECT TOP 5 CATEGORY,
AVG(UNITPRICE) AS AVG_UNIT_PRICE
FROM TORDER
GROUP BY CATEGORY
ORDER BY AVG_UNIT_PRICE DESC;


-- 5. Display the Top 3 payment modes used most frequently.

SELECT TOP 3 PAYMENTMODE,
COUNT(*) AS MOST_FREQUENT
FROM TORDER
GROUP BY PAYMENTMODE
ORDER BY MOST_FREQUENT DESC;


-- 6. Display cities where the total revenue is greater than ₹5,00,000.

SELECT CITY,
SUM(QUANTITY * UNITPRICE) AS TOTAL_REVENUE
FROM TORDER
GROUP BY CITY
HAVING SUM(QUANTITY * UNITPRICE) > 500000;


-- 7. Display categories where the average quantity is greater than 5.

SELECT CATEGORY,
AVG(QUANTITY) AS AVG_QUANTITY
FROM TORDER
GROUP BY CATEGORY
HAVING AVG(QUANTITY) > 5;


-- 8. Display customers who placed at least 5 orders.

SELECT CUSTOMERNAME,
COUNT(*) AS TOTAL_ORDERS
FROM TORDER
GROUP BY CUSTOMERNAME
HAVING COUNT(*) >= 5;


-- 9. Display products sold in more than 3 cities.

SELECT TPRODUCT,
COUNT(DISTINCT CITY) AS TOTAL_CITIES
FROM TORDER
GROUP BY TPRODUCT
HAVING COUNT(DISTINCT CITY) > 3;


-- 10. Display customers who purchased products from more than 2 categories.

SELECT CUSTOMERNAME,
COUNT(DISTINCT CATEGORY) AS TOTAL_CATEGORIES
FROM TORDER
GROUP BY CUSTOMERNAME
HAVING COUNT(DISTINCT CATEGORY) > 2;


-- 11. Display cities having more than 10 distinct customers.

SELECT CITY,
COUNT(DISTINCT CUSTOMERNAME) AS DISTINCT_CUSTOMERS
FROM TORDER
GROUP BY CITY
HAVING COUNT(DISTINCT CUSTOMERNAME) > 10;


-- 12. Display payment modes having more than 100 total quantities sold.

SELECT PAYMENTMODE,
SUM(QUANTITY) AS TOTAL_QUANTITY
FROM TORDER
GROUP BY PAYMENTMODE
HAVING SUM(QUANTITY) > 100;


-- 13. Display the Top 10 products based on the highest average unit price.

SELECT TOP 10 TPRODUCT,
AVG(UNITPRICE) AS AVG_UNIT_PRICE
FROM TORDER
GROUP BY TPRODUCT
ORDER BY AVG_UNIT_PRICE DESC;


-- 14. Display categories where the maximum unit price is greater than ₹50,000.

SELECT CATEGORY,
MAX(UNITPRICE) AS MAX_UNIT_PRICE
FROM TORDER
GROUP BY CATEGORY
HAVING MAX(UNITPRICE) > 50000;


-- 15. Display cities where the minimum unit price is less than ₹5,000.

SELECT CITY,
MIN(UNITPRICE) AS MIN_UNIT_PRICE
FROM TORDER
GROUP BY CITY
HAVING MIN(UNITPRICE) < 5000;


-- 16. Display customers whose maximum purchase quantity is greater than 10.

SELECT CUSTOMERNAME,
MAX(QUANTITY) AS MAX_QUANTITY
FROM TORDER
GROUP BY CUSTOMERNAME
HAVING MAX(QUANTITY) > 10;


-- 17. Display the Top 5 customers having the highest average unit price.

SELECT TOP 5 CUSTOMERNAME,
AVG(UNITPRICE) AS AVG_UNIT_PRICE
FROM TORDER
GROUP BY CUSTOMERNAME
ORDER BY AVG_UNIT_PRICE DESC;


-- 18. Display the Top 10 products sold in the highest total quantity.

SELECT TOP 10 TPRODUCT,
SUM(QUANTITY) AS TOTAL_QUANTITY
FROM TORDER
GROUP BY TPRODUCT
ORDER BY TOTAL_QUANTITY DESC;


-- 19. Display categories whose total revenue is greater than ₹5,00,000.

SELECT CATEGORY,
SUM(QUANTITY * UNITPRICE) AS TOTAL_REVENUE
FROM TORDER
GROUP BY CATEGORY
HAVING SUM(QUANTITY * UNITPRICE) > 500000;


-- 20. Display the Top 5 cities having the highest average revenue per order.

SELECT TOP 5 CITY,
AVG(QUANTITY * UNITPRICE) AS AVG_REVENUE_PER_ORDER
FROM TORDER
GROUP BY CITY
ORDER BY AVG_REVENUE_PER_ORDER DESC;


-- 21. Display customers who purchased more than 10 distinct products.

SELECT CUSTOMERNAME,
COUNT(DISTINCT TPRODUCT) AS DISTINCT_PRODUCTS
FROM TORDER
GROUP BY CUSTOMERNAME
HAVING COUNT(DISTINCT TPRODUCT) > 10;


-- 22. Display categories having at least 5 different products.

SELECT CATEGORY,
COUNT(DISTINCT TPRODUCT) AS DISTINCT_PRODUCTS
FROM TORDER
GROUP BY CATEGORY
HAVING COUNT(DISTINCT TPRODUCT) >= 5;


-- 23. Display payment modes having more than 5 distinct customers.

SELECT PAYMENTMODE,
COUNT(DISTINCT CUSTOMERNAME) AS DISTINCT_CUSTOMERS
FROM TORDER
GROUP BY PAYMENTMODE
HAVING COUNT(DISTINCT CUSTOMERNAME) > 5;


-- 24. Display cities where both the total quantity sold is greater
-- than 100 and the average unit price is greater than ₹20,000.

SELECT CITY,
SUM(QUANTITY) AS TOTAL_QUANTITY,
AVG(UNITPRICE) AS AVG_UNIT_PRICE
FROM TORDER
GROUP BY CITY
HAVING SUM(QUANTITY) > 100
AND AVG(UNITPRICE) > 20000;


-- 25. Display the Top 10 customers based on:
-- Highest total revenue
-- If revenue is the same, higher total quantity
-- If quantity is also the same, alphabetically by customer name.

SELECT TOP 10 CUSTOMERNAME,
SUM(QUANTITY * UNITPRICE) AS TOTAL_REVENUE,
SUM(QUANTITY) AS TOTAL_QUANTITY
FROM TORDER
GROUP BY CUSTOMERNAME
ORDER BY TOTAL_REVENUE DESC,
TOTAL_QUANTITY DESC,
CUSTOMERNAME ASC;